CREATE TABLE ANEXO (
  CODANEXO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CODOCORRENCIA INTEGER UNSIGNED NOT NULL,
  CODUSUARIO INTEGER UNSIGNED NOT NULL,
  CAMINHO LONGTEXT NULL,
  TIPO VARCHAR(10) NULL,
  TAMANHO VARCHAR(50) NULL,
  FLG_ATIVO INTEGER UNSIGNED NULL,
  PRIMARY KEY(CODANEXO),
  INDEX ANEXO_FKIndex1(CODOCORRENCIA, CODUSUARIO)
);

CREATE TABLE ANIMAL (
  CODANIMAL INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TIPO VARCHAR(20) NULL,
  RACA VARCHAR(20) NULL,
  PORTE VARCHAR(20) NULL,
  COLEIRA VARCHAR(3) NULL,
  COLEIRA_COR VARCHAR(15) NULL,
  COLEIRA_IDENTIFICACAO VARCHAR(20) NULL,
  COLEIRA_MARCA VARCHAR(20) NULL,
  DEFICIENCIA VARCHAR(3) NULL,
  CARACTERISTICA LONGTEXT NULL,
  PRIMARY KEY(CODANIMAL)
);

CREATE TABLE ARMAZENAMENTO (
  CODARMAZENAMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TIPO VARCHAR(20) NULL,
  COR VARCHAR(10) NULL,
  MARCA VARCHAR(20) NULL,
  MODELO VARCHAR(20) NULL,
  NSERIE VARCHAR(40) NULL,
  PRIMARY KEY(CODARMAZENAMENTO)
);

CREATE TABLE CARTAO (
  CODCARTAO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TIPO VARCHAR(10) NULL,
  NOME VARCHAR(40) NULL,
  AGENCIA VARCHAR(40) NULL,
  CONTA INTEGER UNSIGNED NULL,
  NUMERO VARCHAR(40) NULL,
  PRIMARY KEY(CODCARTAO)
);

CREATE TABLE DOCUMENTO (
  CODDOCUMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(20) NULL,
  CPF VARCHAR(40) NULL,
  RG VARCHAR(40) NULL,
  TITULO VARCHAR(40) NULL,
  PRIMARY KEY(CODDOCUMENTO)
);

CREATE TABLE ELETRONICO (
  CODELETRONICO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TIPO VARCHAR(20) NULL,
  MARCA VARCHAR(20) NULL,
  MODELO VARCHAR(20) NULL,
  COR TEXT NULL,
  NSERIE VARCHAR(40) NULL,
  IMEI1 VARCHAR(40) NULL,
  IMEI2 VARCHAR(40) NULL,
  IMEI3 VARCHAR(40) NULL,
  IMEI4 VARCHAR(40) NULL,
  PRIMARY KEY(CODELETRONICO)
);

CREATE TABLE JOIA (
  CODJOIA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  MATERIAL VARCHAR(20) NULL,
  TIPO VARCHAR(20) NULL,
  MODELO VARCHAR(20) NULL,
  IDENTIFICACAO VARCHAR(20) NULL,
  PRIMARY KEY(CODJOIA)
);

CREATE TABLE LOCALIZACAO (
  CODLOCALIZACAO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ENDERECO LONGTEXT NULL,
  LATITUDE LONGTEXT NULL,
  LONGITUDE LONGTEXT NULL,
  OBSERVACAO LONGTEXT NULL,
  PRIMARY KEY(CODLOCALIZACAO)
);

CREATE TABLE OBJETO (
  CODOBJETO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TIPO VARCHAR(20) NULL,
  MARCA VARCHAR(20) NULL,
  MODELO VARCHAR(20) NULL,
  OBSERVACOES LONGTEXT NULL,
  PRIMARY KEY(CODOBJETO)
);

CREATE TABLE OCORRENCIA (
  CODOCORRENCIA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CODUSUARIO INTEGER UNSIGNED NOT NULL,
  IDENTIFICADOR VARCHAR(3) NULL,
  DTAP DATETIME NULL,
  POSSE VARCHAR(3) NULL,
  RECOMPENSA VARCHAR(3) NULL,
  CODANIMAL INTEGER UNSIGNED NOT NULL,
  CODARMAZENAMENTO INTEGER UNSIGNED NOT NULL,
  CODCARTAO INTEGER UNSIGNED NOT NULL,
  CODDOCUMENTO INTEGER UNSIGNED NOT NULL,
  CODELETRONICO INTEGER UNSIGNED NOT NULL,
  CODJOIA INTEGER UNSIGNED NOT NULL,
  CODLOCALIZACAO INTEGER UNSIGNED NOT NULL,
  CODOBJETO INTEGER UNSIGNED NOT NULL,
  CODVESTIMENTA INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(CODOCORRENCIA, CODUSUARIO),
  INDEX OCORRENCIA_FKIndex1(CODUSUARIO),
  INDEX OCORRENCIA_FKIndex2(CODANIMAL),
  INDEX OCORRENCIA_FKIndex3(CODDOCUMENTO),
  INDEX OCORRENCIA_FKIndex5(CODELETRONICO),
  INDEX OCORRENCIA_FKIndex6(CODARMAZENAMENTO),
  INDEX OCORRENCIA_FKIndex7(CODOBJETO),
  INDEX OCORRENCIA_FKIndex8(CODJOIA),
  INDEX OCORRENCIA_FKIndex9(CODCARTAO),
  INDEX OCORRENCIA_FKIndex11(CODVESTIMENTA),
  INDEX OCORRENCIA_FKIndex12(CODLOCALIZACAO)
);

CREATE TABLE USUARIO (
  CODUSUARIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(15) NULL,
  SOBRENOME VARCHAR(15) NULL,
  EMAIL VARCHAR(50) NULL,
  SENHA VARCHAR(40) NULL,
  DTCRIACAO DATETIME NULL,
  DTMODIFICACAO DATETIME NULL,
  FLGATIVO INTEGER UNSIGNED NULL,
  PRIMARY KEY(CODUSUARIO)
);

CREATE TABLE VESTIMENTA (
  CODVESTIMENTA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TIPO VARCHAR(20) NULL,
  MARCA VARCHAR(20) NULL,
  MODELO VARCHAR(20) NULL,
  COR VARCHAR(20) NULL,
  DESCRICAO LONGTEXT NULL,
  PRIMARY KEY(CODVESTIMENTA)
);


