					SELECT 
						
							ANEXO.CODANEXO AS ANEXO_CODANEXO,
							ANEXO.CAMINHO AS ANEXO_CAMINHO,
							ANEXO.TIPO AS ANEXO_TIPO,
							ANEXO.TAMANHO AS ANEXO_TAMANHO,
							
							ANIMAL.CODANIMAL AS ANIMAL_CODANIMAL,
							ANIMAL.RACA AS ANIMAL_RACA, 
							ANIMAL.PORTE AS ANIMAL_PORTE,
							ANIMAL.COLEIRA AS ANIMAL_COLEIRA,
							ANIMAL.COLEIRA_COR AS ANIMAL_COLEIRA_COR,
							ANIMAL.COLEIRA_IDENTIFICACAO AS ANIMAL_COLEIRA_IDENTIFICACAO,
							ANIMAL.DEFICIENCIA AS ANIMAL_DEFICIENCIA,
							ANIMAL.CARACTERISTICA AS ANIMAL_CARACTERISTICA,
						
						
							ARMAZENAMENTO.CODARMAZENAMENTO AS ARMAZENAMENTO_CODARMAZENAMENTO, 
						 	ARMAZENAMENTO.TIPO AS ARMAZENAMENTO_TIPO,
							ARMAZENAMENTO.COR AS ARMAZENAMENTO_COR,
							ARMAZENAMENTO.MARCA AS ARMAZENAMENTO_MARCA,
							ARMAZENAMENTO.NSERIE AS ARMAZENAMENTO_NSERIE,				
						
							CARTAO.CODCARTAO AS CARTAO_CODCARTAO,
							CARTAO.TIPO AS CARTAO_TIPO,
							CARTAO.NOME AS CARTAO_NOME,
							CARTAO.AGENCIA AS CARTAO_AGENCIA,
							CARTAO.CONTA AS CARTAO_CONTA,
							CARTAO.NUMERO AS CARTAO_NUMERO,
						
							DOCUMENTO.CODDOCUMENTO AS DOCUMENTO_CODDOCUMENTO,
							DOCUMENTO.CPF AS DOCUMENTO_CPF, 
							DOCUMENTO.RG AS DOCUMENTO_RG,
							DOCUMENTO.TITULO AS DOCUMENTO_TITULO,			
						
							ELETRONICO.CODELETRONICO AS ELETRONICO_CODELETRONICO,
							ELETRONICO.TIPO AS ELETRONICO_TIPO, 
							ELETRONICO.MARCA AS ELETRONICO_MARCA,
							ELETRONICO.MODELO AS ELETRONICO_MODELO,
							ELETRONICO.NSERIE AS ELETRONICO_NSERIE,
							ELETRONICO.IMEI1 AS ELETRONICO_IMEI1, 
							ELETRONICO.IMEI2 AS ELETRONICO_IMEI2,
							ELETRONICO.IMEI3 AS ELETRONICO_IMEI3,
							ELETRONICO.IMEI4 AS ELETRONICO_IMEI4,
						
							JOIA.CODJOIA AS JOIA_CODJOIA,
							JOIA.MATERIAL AS JOIA_MATERIAL,
							JOIA.TIPO AS JOIA_TIPO, 
							JOIA.MODELO AS JOIA_MODELO, 
							JOIA.IDENTIFICACAO AS JOIA_IDENTIFICACAO,
							
							LOCALIZACAO.CODLOCALIZACAO AS LOCALIZACAO_CODLOCALIZACAO,
							LOCALIZACAO.ENDERECO AS LOCALIZACAO_ENDERECO,
							LOCALIZACAO.LATITUDE AS LOCALIZACAO_LATITUDE,
							LOCALIZACAO.LONGITUDE AS LOCALIZACAO_LONGITUDE,
							LOCALIZACAO.OBSERVACAO AS LOCALIZACAO_OBSERVACAO,
					
					   	OBJETO.CODOBJETO AS OBJETO_CODOBJETO,
					  		OBJETO.TIPO AS OBJETO_TIPO,
					   	OBJETO.MARCA AS OBJETO_MARCA,
						  	OBJETO.MODELO AS OBJETO_MODELO,
					   	OBJETO.OBSERVACOES AS OBJETO_OBSERVACOES,
					
							VESTIMENTA.CODVESTIMENTA AS VESTIMENTA_CODVESTIMENTA,
							VESTIMENTA.TIPO AS VESTIMENTA_TIPO,
							VESTIMENTA.MARCA AS VESTIMENTA_MARCA,
							VESTIMENTA.MODELO AS VESTIMENTA_MODELO,
							VESTIMENTA.COR AS VESTIMENTA_COR,
							VESTIMENTA.DESCRICAO AS VESTIMENTA_DESCRICAO
							
									FROM OCORRENCIA
					
					LEFT JOIN ANEXO ON ANEXO.CODANEXO = OCORRENCIA.CODANEXO
					LEFT JOIN ANIMAL ON ANIMAL.CODANIMAL = OCORRENCIA.CODANIMAL
					LEFT JOIN ARMAZENAMENTO ON ARMAZENAMENTO.CODARMAZENAMENTO = OCORRENCIA.CODARMAZENAMENTO
					LEFT JOIN CARTAO ON CARTAO.CODCARTAO=OCORRENCIA.CODCARTAO
					LEFT JOIN DOCUMENTO ON DOCUMENTO.CODDOCUMENTO = OCORRENCIA.CODDOCUMENTO
					LEFT JOIN ELETRONICO ON ELETRONICO.CODELETRONICO = OCORRENCIA.CODELETRONICO
					LEFT JOIN JOIA ON JOIA.CODJOIA = OCORRENCIA.CODJOIA
					LEFT JOIN LOCALIZACAO ON LOCALIZACAO.CODLOCALIZACAO = OCORRENCIA.CODLOCALIZACAO
					LEFT JOIN OBJETO ON OBJETO.CODOBJETO = OCORRENCIA.CODOBJETO
					LEFT JOIN VESTIMENTA ON VESTIMENTA.CODVESTIMENTA = OCORRENCIA.CODVESTIMENTA
					
					WHERE 
					
					OCORRENCIA.IDENTIFICADOR=1